### ISSUE TITLE
[Feature request] Ability to include python files instead of lua code for CX II/II-T

### ISSUE THREAD

**Issue by dimaguy** [ndless-nspire/Luna#15]
I wonder if is feasible to use python code instead of lua to be more inclusive, the documentation on this seems pretty scarce

**Comment by adriweb** [comment]
Yeah it should be, and I've been meaning to add proper support for it, but I've kinda forgotten about it... I'll try to come back to that soon 👀

**Comment by 314gomes** [comment]
It seems only a very simple Problem1.xml is needed for python support and it just needs to contain the filename for the plaintext python file. The student software adds aditional information on Problem1.xml but I was able to generate valid TNS python programs without them.

Would it be "proper support" to automatically generate this Problem1.xml?

**Comment by dimaguy** [comment]
I'm not exactly picky, as long as whatever path ends in a usable tns file it's all fair game

**Comment by sasdallas** [comment]
> It seems only a very simple Problem1.xml is needed for python support and it just needs to contain the filename for the plaintext python file. The student software adds aditional information on Problem1.xml but I was able to generate valid TNS python programs without them.
> 
> Would it be "proper support" to automatically generate this Problem1.xml?

Any examples of this additional information?
Most likely nothing, but just to be sure.

**Comment by Legimet** [comment]
Python support added in https://github.com/ndless-nspire/Luna/pull/22

**Comment by dimaguy** [comment]
I will be closing down this issue as it seems to be solved!
