### ISSUE TITLE
Templates for Document.xml and Problem.xml

### ISSUE THREAD

**Issue by HoleInOneGolfer** [ndless-nspire/Luna#19]
Templates for Document.xml and Problem.xml????

**Comment by akpi816218** [comment]
Yup, need to know the format for the XML input document.

**Comment by MaxBas** [comment]
I would love that too, with all new nspire devices unsopported by ndless it is increasingly unaccessible to get the xml oneself. Therefore I would appriciate if one with os version < 5.4.0 could provide some xml files generated from simple problems such a how functions are saved, graphs (in different equations) and maybe other pages. If someone with said version requirement is willing to, I would greatly appriciate the effort.

**Comment by Legimet** [comment]
@MaxBas The XML format is proprietary and incredibly verbose, see the [example](https://ndlessly.wordpress.com/2011/09/19/luna-updated-for-third-party-tns-document-generation/) of a simple "hello world" notes document. So no one here will be able to provide you with a complete specification. That said, [here](https://gist.github.com/Legimet/14bda1106fc63520f2c12412231eaf31) is a sample `Document.xml`. Replace the number in the <nps> tag with the number of "Problem*.xml" files. If you have a particular TNS file and you want the XML, I'd be happy to extract it for you.

**Comment by MaxBas** [comment]
I just moved so I'm a bit short on time, but once I've got time (maybe in like 1 or 2 weeks) I'll look into preparing a tns that should include most relevant stuff. Thanks for your help @Legimet  :)

**Comment by MaxBas** [comment]
I would appreciate if you could convert some of mine :D
I selected 5 that should cover most of the stuff I'm doing.
[conv.zip](https://github.com/user-attachments/files/15954714/conv.zip)

**Comment by Legimet** [comment]
Here you go: [conv.zip](https://github.com/user-attachments/files/15981276/conv.zip)

**Comment by MaxBas** [comment]
I would have formatted it using a N++ plugin before, but that seems way more convenient. Thanks for the conversion :)
