### ISSUE TITLE
Allow including resources in the files as per api level 2.3

### ISSUE THREAD

**Issue by poutros** [ndless-nspire/Luna#2]
https://education.ti.com/html/webhelp/EG_TINspireLUA/EN/content/libraries/ab_depapifuncapibehav/deprecatedapifunctionsapi%20behavior.htm#Image

Images as strings have been deprecated as per api level 2.3 and now have to be included as resources instead.

**Comment by Vogtinator** [comment]
luna can already pack arbitrary files into the .tns, so only the ProblemX.xml needs to reference it properly.

**Comment by poutros** [comment]
How do I do that then?
