### ISSUE TITLE
Problems with running Luna

### ISSUE THREAD

**Issue by SophisticatedFox4** [ndless-nspire/Luna#21]
Hello,
I've tried to convert this .lua file into a .tns file, but the instructions aren't very clear. Do I have to build it, or can I just run it in terminal by going to the file and calling "luna"?
Thank you.
P.S. Here is the .lua file I am trying to convert; can you turn it to a .tns file for me? Thanks a lot!
[periodic.lua.zip](https://github.com/user-attachments/files/15895612/periodic.lua.zip)

**Comment by Legimet** [comment]
Did you try following the directions in the README? It should just work.

**Comment by adriweb** [comment]
Looks like I need to set up a macOS CI that produces binaries like the windows one :) although a web wasm would be even better (why not both though)

**Comment by Legimet** [comment]
There are Windows binaries? Where?

**Comment by adriweb** [comment]
At the bottom of each CI run page, for instance here https://github.com/ndless-nspire/Luna/actions/runs/9587792813

**Comment by Legimet** [comment]
Oh OK. I didn't know because the releases page only has source code downloads. (I don't use Windows so it doesn't matter for me.)

**Comment by adriweb** [comment]
We can similarly provide Linux binaries but the target audience likely target actually need that. Doesn't hurt to have CI to make sure everything builds fine though

**Comment by SophisticatedFox4** [comment]
For more information, I'm using macos. I tried following readme, but when I ran the code "cd Luna-2.1(I'm not listing the complete directory here)", and then tried calling "luna", it gives me the error, "zsh: command not found: luna." How do I fix this?

**Comment by Legimet** [comment]
As discussed above, there are currently no binaries for macOS. Luna is a C program so you will have to compile it from source. Scroll down to the "building it yourself section" of the Readme and follow the instructions. You will need Homebrew: https://brew.sh/

**Comment by SophisticatedFox4** [comment]
Okay, I've followed all the instructions, installed homebrew and zlib, and ran make. However, when I type only "luna" into the command line, it still says "unknown command". What is the exact code I must run to call luna?
Thanks a lot!

**Comment by Vogtinator** [comment]
`./luna` or with the full path to the build directory.

**Comment by SophisticatedFox4** [comment]
Ok, thanks!
