### ISSUE TITLE
Lua scripts containing the string "]]>" result in malformed TNS

### ISSUE THREAD

**Issue by Legimet** [ndless-nspire/Luna#26]
Luna produces a malformed TNS when run on a Lua script containing "]]>" such as the following:

```
function on.paint(gc)
	gc:drawString("]]>", 5, 20)
end
```

This is because according to the [XML spec](https://www.w3.org/TR/xml/#syntax),
> The right angle bracket (>) may be represented using the string " &gt; ", and MUST, [for compatibility](https://www.w3.org/TR/xml/#dt-compat), be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a [CDATA section](https://www.w3.org/TR/xml/#dt-cdsection).

Alternatively, we could place the Lua script in a CDATA section (I believe this is what the TI software does), not escape any characters, and replace all instances of `]]>` with `]]]]><![CDATA[>`. I personally prefer this solution but could make a PR to implement either.

**Comment by Vogtinator** [comment]
There's already code to convert `&` and `<`  to `&amp;` and `&lt;` resp., so converting `>` to `&gt;` is probably the easiest option.

**Comment by Legimet** [comment]
I was able to do it using CDATA, and simplify the code a bit in the process. Will submit a PR shortly.

Also, stay tuned for a few more bug reports.
