### ISSUE TITLE
Allow specifiying api level

### ISSUE THREAD

**Issue by poutros** [ndless-nspire/Luna#3]
Given some deprecations and additions between apis, it would be useful to be able to specify the api level.

**Comment by Vogtinator** [comment]
That's usually done in the ProblemX.xml itself, so luna does not need to implement this.

**Comment by poutros** [comment]
How do I structure the Problem1.xml file to have purely the api reference I want? Can I instead put the api reference in the lua file or will luna ignore it and add the default reference itself?

**Comment by adriweb** [comment]
there's a "taral" attribute in the XML, but specifying `platform.apilevel = '...'` in the first line of the script itself should work just as well.
