### ISSUE TITLE
Remove OpenSSL dependency

### ISSUE THREAD

**Issue by adriweb** [ndless-nspire/Luna#4]
Just so that this idea isn't forgotten...

Basically, remove as many deps as possible especially OpenSSL, so that it can be built easily with emscripten/wasm.

**Comment by Legimet** [comment]
I plan to make a PR allowing Luna to build with OpenSSL 1.1. I don't know what 
would need to be done to get rid of the OpenSSL dependency altogether.

**Comment by adriweb** [comment]
Might be worth looking at those:
- https://github.com/mimoo/DES
- https://github.com/tarequeh/DES
